# Generated by Django 3.0.6 on 2020-05-25 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('first_last', models.IntegerField()),
                ('total_strength', models.IntegerField()),
                ('commander_strength', models.IntegerField()),
                ('personnel_strength', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parade_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parade_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_commander', models.BooleanField(default=False)),
                ('platoon', models.IntegerField()),
                ('company', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('remarks', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL)),
                ('parade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Parade')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Personnel')),
                ('updated_by', models.ForeignKey(db_column='updated_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_MC', models.BooleanField(default=False)),
                ('is_MA', models.BooleanField(default=False)),
                ('is_off', models.BooleanField(default=False)),
                ('is_leave', models.BooleanField(default=False)),
                ('is_other', models.BooleanField(default=False)),
                ('remarks', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='absence_created_by', to=settings.AUTH_USER_MODEL)),
                ('parade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Parade')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Personnel')),
                ('updated_by', models.ForeignKey(db_column='updated_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='absence_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
