# Generated by Django 3.0.7 on 2020-07-09 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200709_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='parade',
            name='current_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parade',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
