# Generated by Django 3.0.7 on 2020-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200713_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parade',
            name='commander_strength',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parade',
            name='current_strength',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parade',
            name='personnel_strength',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='parade',
            name='total_strength',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
