# Generated by Django 3.0.8 on 2020-07-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_paradepersonnel_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parade',
            name='disrepancy',
            field=models.BooleanField(default=False),
        ),
    ]
