# Generated by Django 3.0.8 on 2020-07-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_parade_disrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parade',
            name='disrepancy',
            field=models.BooleanField(default=None),
        ),
    ]
