# Generated by Django 3.0.8 on 2020-07-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20200723_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parade',
            old_name='disrepancy',
            new_name='disrepancy_override',
        ),
    ]
