# Generated by Django 3.0.8 on 2020-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20200723_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parade',
            name='ignore_discrepancy',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
